// Generated by CoffeeScript 1.12.4
var CRYPTO, colors, fs, path, rp;

colors = require('colors');

path = require('path');

fs = require('fs');

rp = require('request-promise');

CRYPTO = {
  getBchAddress: function(options) {
    return rp({
      uri: "https://blockdozer.com/insight-api/addr/" + options.address,
      json: true
    });
  },
  getTokenPrice: function(options) {
    return rp({
      uri: "https://api.coinmarketcap.com/v1/ticker/" + options.token + "/",
      json: true
    });
  }
};

module.exports = CRYPTO;
